USE [NZBS]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[nzbDirectedTransferOrderFormItems] AS
SELECT A1.DT_ORDER_FORMSID_OrderFormID AS ORDER_ID,
       A1.DT_ORDER_FORMS_190_ItemNumber AS ITEMNMBR,
       A1.DT_ORDER_FORMS_191_Zone AS ZONE,
       A1.DT_ORDER_FORMS_192_OrderPriority AS PRIORITY
FROM (
    SELECT f.UD_Form_Field_ID AS DT_ORDER_FORMSID_OrderFormID,
           B190.DT_ORDER_FORMS_190_ItemNumber,
           B191.DT_ORDER_FORMS_191_Zone,
           B192.DT_ORDER_FORMS_192_OrderPriority
    FROM EXT01200 f
    LEFT JOIN EXT01210 l ON l.Extender_Record_ID=f.Extender_Record_ID
    LEFT JOIN (SELECT Extender_Record_ID, STRGA255 AS DT_ORDER_FORMS_190_ItemNumber, LNITMSEQ FROM EXT01211 WHERE Field_ID=190) B190 ON l.Extender_Record_ID=B190.Extender_Record_ID AND l.LNITMSEQ=B190.LNITMSEQ
    LEFT JOIN (SELECT Extender_Record_ID, STRGA255 AS DT_ORDER_FORMS_191_Zone, LNITMSEQ FROM EXT01211 WHERE Field_ID=191) B191 ON l.Extender_Record_ID=B191.Extender_Record_ID AND l.LNITMSEQ=B191.LNITMSEQ
    LEFT JOIN (SELECT Extender_Record_ID, TOTAL AS DT_ORDER_FORMS_192_OrderPriority, LNITMSEQ FROM EXT01213 WHERE Field_ID=192) B192 ON l.Extender_Record_ID=B192.Extender_Record_ID AND l.LNITMSEQ=B192.LNITMSEQ
    WHERE f.Extender_Form_ID='DT_ORDER_FORMS'
) A1
GO
